
ALTER TABLE public.tax_settings
  ADD COLUMN IF NOT EXISTS filing_status TEXT NOT NULL DEFAULT 'single',
  ADD COLUMN IF NOT EXISTS last_year_tax NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS standard_deduction_override NUMERIC,
  ADD COLUMN IF NOT EXISTS ss_wage_cap NUMERIC NOT NULL DEFAULT 168600;
